Already on 'addinggriffin'
wandb: Currently logged in as: stevenzhou0816100. Use `wandb login --relogin` to force relogin
The following values were not passed to `accelerate launch` and had defaults used instead:
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:  25%|██▌       | 1/4 [00:20<01:01, 20.49s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:20<01:02, 20.96s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:20<01:02, 20.99s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:21<01:03, 21.02s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:21<01:03, 21.18s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:20<01:02, 20.91s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:21<01:03, 21.02s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:21<01:03, 21.30s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:38<00:38, 19.17s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:39<00:39, 19.80s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:40<00:39, 19.86s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:40<00:39, 19.91s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:40<00:39, 19.89s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:40<00:40, 20.22s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:40<00:39, 19.98s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:40<00:39, 19.91s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:54<00:17, 17.20s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:54<00:17, 17.50s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:54<00:17, 17.52s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:55<00:17, 17.73s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:54<00:17, 17.56s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:55<00:17, 17.76s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:54<00:17, 17.55s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:54<00:17, 17.55s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:56<00:00, 11.31s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:56<00:00, 14.15s/it]
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/CommonSenseReasoning/mainfordebugging.py", line 111, in <module>
    model = get_llama_griffin_no_tree(model, schedule_k, patternstrict = args.patternstrict) 
TypeError: get_llama_griffin_no_tree() got an unexpected keyword argument 'patternstrict'
Loading checkpoint shards: 100%|██████████| 4/4 [00:56<00:00, 11.38s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:56<00:00, 14.17s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:56<00:00, 11.51s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:56<00:00, 14.24s/it]
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/CommonSenseReasoning/mainfordebugging.py", line 111, in <module>
    model = get_llama_griffin_no_tree(model, schedule_k, patternstrict = args.patternstrict) 
TypeError: get_llama_griffin_no_tree() got an unexpected keyword argument 'patternstrict'
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/CommonSenseReasoning/mainfordebugging.py", line 111, in <module>
    model = get_llama_griffin_no_tree(model, schedule_k, patternstrict = args.patternstrict) 
TypeError: get_llama_griffin_no_tree() got an unexpected keyword argument 'patternstrict'
Loading checkpoint shards: 100%|██████████| 4/4 [00:56<00:00, 11.40s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:56<00:00, 14.22s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:56<00:00, 11.41s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:56<00:00, 14.22s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:57<00:00, 11.53s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:57<00:00, 14.27s/it]
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/CommonSenseReasoning/mainfordebugging.py", line 111, in <module>
    model = get_llama_griffin_no_tree(model, schedule_k, patternstrict = args.patternstrict) 
TypeError: get_llama_griffin_no_tree() got an unexpected keyword argument 'patternstrict'
Loading checkpoint shards: 100%|██████████| 4/4 [00:56<00:00, 11.41s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:57<00:00, 11.52s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:56<00:00, 14.22s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:57<00:00, 14.32s/it]
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/CommonSenseReasoning/mainfordebugging.py", line 111, in <module>
    model = get_llama_griffin_no_tree(model, schedule_k, patternstrict = args.patternstrict) 
TypeError: get_llama_griffin_no_tree() got an unexpected keyword argument 'patternstrict'
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/CommonSenseReasoning/mainfordebugging.py", line 111, in <module>
    model = get_llama_griffin_no_tree(model, schedule_k, patternstrict = args.patternstrict) 
TypeError: get_llama_griffin_no_tree() got an unexpected keyword argument 'patternstrict'
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/CommonSenseReasoning/mainfordebugging.py", line 111, in <module>
    model = get_llama_griffin_no_tree(model, schedule_k, patternstrict = args.patternstrict) 
TypeError: get_llama_griffin_no_tree() got an unexpected keyword argument 'patternstrict'
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/CommonSenseReasoning/mainfordebugging.py", line 111, in <module>
    model = get_llama_griffin_no_tree(model, schedule_k, patternstrict = args.patternstrict) 
TypeError: get_llama_griffin_no_tree() got an unexpected keyword argument 'patternstrict'
[2024-07-13 02:00:41,534] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 917286) of binary: /fsx-storygen/beidic/anaconda3/envs/griffin/bin/python3.9
Traceback (most recent call last):
  File "/fsx-storygen/beidic/anaconda3/envs/griffin/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/accelerate/commands/launch.py", line 985, in launch_command
    multi_gpu_launcher(args)
  File "/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/accelerate/commands/launch.py", line 654, in multi_gpu_launcher
    distrib_run.run(args)
  File "/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
mainfordebugging.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-13_02:00:41
  host      : a100-st-p4de24xlarge-799.fair-a100.hpcaas
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 917287)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-07-13_02:00:41
  host      : a100-st-p4de24xlarge-799.fair-a100.hpcaas
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 917288)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-07-13_02:00:41
  host      : a100-st-p4de24xlarge-799.fair-a100.hpcaas
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 917289)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-07-13_02:00:41
  host      : a100-st-p4de24xlarge-799.fair-a100.hpcaas
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 917290)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-07-13_02:00:41
  host      : a100-st-p4de24xlarge-799.fair-a100.hpcaas
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 917291)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-07-13_02:00:41
  host      : a100-st-p4de24xlarge-799.fair-a100.hpcaas
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 917292)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2024-07-13_02:00:41
  host      : a100-st-p4de24xlarge-799.fair-a100.hpcaas
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 917293)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-13_02:00:41
  host      : a100-st-p4de24xlarge-799.fair-a100.hpcaas
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 917286)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
